routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::resource('daftar','RegistrationController');
Route::get('daftar-sukses', 'RegistrationController@successReg')->name('daftar-sukses');
Route::post('post-register', 'RegistrationController@store')->name('post-register');
Route::get('kel', 'RegistrationController@getKelurahan')->name('kel');
Route::get('kec', 'RegistrationController@getKecamatan')->name('kec');
Route::get('kab', 'RegistrationController@getKabupaten')->name('kab');
Route::get('verify', 'RegistrationController@verify')->name('daftar.verify');

Route::get('change-passwords', 'ChangePasswordController@index')->name('change-passwords');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

Route::get('img/articles/{filename}', 'ImgController@displayArticles')->name('img.articles');
Route::get('img/thumbnail/{filename}', 'ImgController@displayThumbnail')->name('img.thumbnail');
Route::get('img/avatar/{filename}', 'ImgController@displayAvatar')->name('img.avatar');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');
    Route::resource('customer', 'CustomerController');

    Route::resource('item-category', 'ItemCategoryController');
    
    Route::resource('item-unit', 'ItemUnitController');

    Route::resource('item', 'ItemController');
    Route::get('create-packet', 'ItemController@createPacket')->name('create-packet');
    Route::post('post-packet', 'ItemController@postPacket')->name('post-packet');
    Route::get('edit-packet', 'ItemController@editPacket')->name('edit-packet');
    Route::get('show-packet/{id}', 'ItemController@showPacket')->name('show-packet');

    //Transaction
    Route::resource('transaksi', 'TransaksiStokController');
    Route::get('transaksi-in','TransaksiStokController@createIn')->name('transaksi-in');
    Route::get('transaksi-out','TransaksiStokController@createOut')->name('transaksi-out');
    Route::post('transaksi-store-out','TransaksiStokController@storeOut')->name('transaksi-store-out');
    Route::get('report-transaksi', 'TransaksiStokController@reportTransaksi')->name('report-transaksi');
    

    //RO
    Route::resource('ro', 'RequestOrderController');
    Route::get('report-ro', 'RequestOrderController@reportRO')->name('report-ro');
    
    //PO
    Route::resource('po', 'PurchaseOrderController');
    Route::put('update-payment/{id}', 'PurchaseOrderController@updatePayment')->name('update-payment');
    Route::get('report-po', 'PurchaseOrderController@reportPO')->name('report-po');

    //Information
    Route::resource('info', 'InformationController');
    Route::resource('category', 'ArticleCategoryController');

    //getImage
    Route::get('img/ktp/{filename}', 'ImgController@displayKtp')->name('img.ktp');
    Route::get('img/kk/{filename}', 'ImgController@displayKK')->name('img.kk');
    Route::get('img/avatar/{filename}', 'ImgController@displayAvatar')->name('img.avatar');
    Route::get('img/articles/{filename}', 'ImgController@displayArticles')->name('img.articles');
    Route::get('img/thumbnail/{filename}', 'ImgController@displayThumbnail')->name('img.thumbnail');
    
    

    //Master
    Route::resource('gudang', 'GudangController');
    Route::put('rak-update-partial', 'GudangController@updateRakPartials')->name('rak-update-partial');
    Route::put('rak-add-partial', 'GudangController@addRakPartials')->name('rak-add-partial');
    Route::put('rak-del-partial', 'GudangController@delRakPartials')->name('rak-del-partial');
    Route::resource('supplier', 'SupplierController');
    Route::resource('program', 'ProgramController');
    Route::get('report-program', 'ProgramController@reportProgram')->name('report-program');
    Route::resource('wilayah', 'WilayahController');
    Route::resource('provinsi', 'ProvinsiController');
    Route::get('report-member-prov/{id}', 'ProvinsiController@reportMember')->name('report-member-prov');
    Route::resource('kabupaten', 'KabupatenController');
    Route::get('report-member-kab/{id}', 'KabupatenController@reportMember')->name('report-member-kab');
    Route::resource('kecamatan', 'KecamatanController');
    Route::get('report-member-kec/{id}', 'KecamatanController@reportMember')->name('report-member-kec');
    Route::resource('kelurahan', 'KelurahanController');
    Route::get('report-member-kel/{id}', 'KelurahanController@reportMember')->name('report-member-kel');
    Route::resource('master-member', 'MemberController');
    Route::get('report-member', 'MemberController@reportMember')->name('report-member');
    Route::get('member-verified', 'MemberController@indexVerified')->name('member-verified');
    Route::get('edit-verified', 'MemberController@editVerified')->name('edit-verified');
    Route::put('update-verified', 'MemberController@editVerified')->name('update-verified');
    Route::get('edit-korlap/{id}', 'MemberController@editKorlap')->name('edit-korlap');
    Route::put('update-korlap/{id}', 'MemberController@updateKorlap')->name('update-korlap');
    Route::get('member-pending', 'MemberController@indexPending')->name('member-pending');

    //Settings
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');
    Route::get('configuration','ConfigurationController@index')->name('configuration.index');
    Route::get('configuration/create','ConfigurationController@create')->name('configuration.create');
    Route::get('configuration/edit/{id}','ConfigurationController@edit')->name('configuration.edit');
    Route::put('configuration/update/{id}','ConfigurationController@update')->name('configuration.update');
    Route::post('configuration/store','ConfigurationController@store')->name('configuration.store');

    //helper
    Route::get('get-kel', 'HelperController@getKelurahan')->name('get-kel');
    Route::get('get-kec', 'HelperController@getKecamatan')->name('get-kec');
    Route::get('get-kab', 'HelperController@getKabupaten')->name('get-kab');
    Route::get('get-member', 'HelperController@getMember')->name('get-member');
    Route::get('get-rak', 'HelperController@getRak')->name('get-rak');
    
});

resources/views/admin/info/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.information.title_singular') }}
    </div>

    <div class="card-body">
        <form class="form-material mt-4" action="{{ route("admin.info.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
                <label for="nama">{{ trans('cruds.information.fields.nama') }}*</label>
                <input type="text" id="nama" name="nama" class="form-control" value="{{ old('nama', '') }}">
                @if($errors->has('nama'))
                    <em class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('kategori_id') ? 'has-error' : '' }}">
                <label for="kategori_id">{{ trans('cruds.information.fields.categories') }}*</label>
                <select name="kategori_id" id="kategori_id" class="form-control select2" required style="width: 100%; height:36px;">
                    <option value="">{{ trans('global.pleaseSelect') }}</option>
                    @foreach($category as $data => $row)
                        <option value="{{ $data }}" >{{ $row }}</option>
                    @endforeach
                </select>
                @if($errors->has('kategori_id'))
                    <em class="invalid-feedback">
                        {{ $errors->first('kategori_id') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('foto') ? 'has-error' : '' }}">
                <label for="kode">{{ trans('cruds.information.fields.pict') }}*</label>
                <input type="file" id="foto" name="foto" class="form-control" value="{{ old('foto', '') }}">
                @if($errors->has('foto'))
                    <em class="invalid-feedback">
                        {{ $errors->first('foto') }}
                    </em>
                @endif
                <p class="helper-block">
                </p>
            </div>
            <div class="form-group">
                <label for="content">{{ trans('cruds.information.fields.content') }}*</label>
                <textarea class ="form-control my-editor" name="content" value="{{ old('alamat', isset($user) ? $member->alamat : '') }}" id="content"> </textarea>
                @if($errors->has('content'))
                    <em class="invalid-feedback">
                        {{ $errors->first('content') }}
                    </em>
                @endif
            </div>
            <div>
                <button class="btn btn-primary" id="save" type="submit">
                    <span class="spinner-border spin-save spinner-border-sm" role="status" aria-hidden="true"></span>
                    <i class="fa fa-save"></i> {{ trans('global.save') }}
                </button>
                <a href="{{ route('admin.info.index') }}" class="btn btn-default"> 
                    <i class="fa fa-arrow-left"> {{ trans('global.back_to_list') }}</i>
                </a>
            </div>
        </form>


    </div>
</div>
@endsection
@section('scripts')
    @parent
    <script>
        tinymce.init({
            selector:'textarea.my-editor',
            width: 900,
            height: 300
        });
    </script>
@endsection

resources/views/admin/info/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit', ) }} {{ trans('cruds.information.title_singular') }}
    </div>

    <div class="card-body">
        <form class="form-material mt-4" action="{{ route("admin.info.update", $info->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
                <label for="nama">{{ trans('cruds.information.fields.nama') }}*</label>
                <input type="text" id="nama" name="nama" class="form-control" value="{{ $info->name }}">
                @if($errors->has('nama'))
                    <em class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('kategori_id') ? 'has-error' : '' }}">
                <label for="kategori_id">{{ trans('cruds.information.fields.categories') }}*</label>
                <select name="kategori_id" id="kategori_id" class="form-control select2" required style="width: 100%; height:36px;">
                    <option value="">{{ trans('global.pleaseSelect') }}</option>
                    @foreach($category as $data => $row)
                        <option value="{{ $data }}" @if ($info->kategori_id == $data) selected @endif>{{ $row }}</option>
                    @endforeach
                </select>
                @if($errors->has('kategori_id'))
                    <em class="invalid-feedback">
                        {{ $errors->first('kategori_id') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('foto') ? 'has-error' : '' }}">
                <label for="kode">{{ trans('cruds.information.fields.pict') }}*</label>
                <input type="file" id="foto" name="foto" class="form-control" value="{{ old('foto', '') }}">
                @if($errors->has('foto'))
                    <em class="invalid-feedback">
                        {{ $errors->first('foto') }}
                    </em>
                @endif
                <p class="helper-block">
                </p>
            </div>
            <div class="form-group">
                <label for="content">{{ trans('cruds.information.fields.content') }}*</label>
                <textarea class ="form-control my-editor" name="content" value="" id="content"> {{ $info->content }}</textarea>
                @if($errors->has('content'))
                    <em class="invalid-feedback">
                        {{ $errors->first('content') }}
                    </em>
                @endif
            </div>
            <div>
                <button class="btn btn-primary" id="save" type="submit">
                    <span class="spinner-border spin-save spinner-border-sm" role="status" aria-hidden="true"></span>
                    <i class="fa fa-save"></i> {{ trans('global.save') }}
                </button>
                <a href="{{ route('admin.info.index') }}" class="btn btn-default"> 
                    <i class="fa fa-arrow-left"> {{ trans('global.back_to_list') }}</i>
                </a>
            </div>
        </form>


    </div>
</div>
@endsection
@section('scripts')
    @parent
    <script>
        tinymce.init({
            selector:'textarea.my-editor',
            width: 900,
            height: 300
        });
    </script>
@endsection

resources/views/admin/info/index.blade.php
@extends('layouts.admin')
@section('content')
@can('customer_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary float-right" href="{{ route("admin.info.create") }}">
                <i class="fa fa-plus"></i> {{ trans('global.add') }} {{ trans('cruds.information.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.information.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.information.fields.nama') }}
                        </th>
                        <th>
                            {{ trans('cruds.information.fields.categories') }}
                        </th>
                        <th>
                            {{ trans('cruds.information.fields.pict') }}
                        </th>
                        <th>
                            {{ trans('cruds.information.fields.status') }}
                        </th>
                        <th>
                            {{ trans('cruds.information.fields.created_by') }}
                        </th>
                        <th>
                            {{ trans('cruds.information.fields.updated_by') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($info as $key => $rows)
                        <tr data-entry-id="{{ $rows->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $rows->name ?? '' }}
                            </td>
                            <td>
                                @php
                                    $name = \App\ArticleCategory::getCategory($rows->kategori_id)
                                @endphp
                                {{ $name->name ?? '' }}
                            </td>
                            <td>
                                <img width=100 src="{{ asset('images/articles/'.($rows->gambar)) }}"> 
                                {{--<img width=100 src="{{ route('admin.img.articles/',$rows->gambar) }}">--}}
                            </td>
                            <td>
                                @if($rows->is_active == 1)
                                    {{ trans('cruds.member.fields.active') }}
                                @elseif($rows->is_active == 0)
                                    {{ trans('cruds.member.fields.inactive') }}
                                @endif
                            </td>
                            <td>
                                @php
                                    $name = \App\User::getName($rows->created_by);
                                @endphp
                                {{ $name->name ?? '' }}
                            </td>
                            <td>
                                @php
                                    $name = \App\User::getName($rows->updated_by);
                                @endphp
                                {{ $name->name ?? '' }}
                            </td>
                            <td>
                                @can('customer_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.info.show', $rows->id) }}">
                                        <i class="fa fa-eye"></i> {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('customer_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.info.edit', $rows->id) }}">
                                        <i class="fa fa-edit"></i> {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('customer_delete')
                                    
                                    <form action="{{ route('admin.info.destroy', $rows->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">
                                            <i class="fa fa-trash"></i> 
                                            {{ trans('global.delete') }}
                                        </button>
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
        let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
        let deleteButton = {
            text: deleteButtonTrans,
            url: "{{ route('admin.permissions.massDestroy') }}",
            className: 'btn-danger',
            action: function (e, dt, node, config) {
                var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                    return $(entry).data('entry-id')
                });
                if (ids.length === 0) {
                    alert('{{ trans('global.datatables.zero_selected') }}')
                    return
                }
                if (confirm('{{ trans('global.areYouSure') }}')) {
                    $.ajax({
                    headers: {'x-csrf-token': _token},
                    method: 'POST',
                    url: config.url,
                    data: { ids: ids, _method: 'DELETE' }})
                    .done(function () { location.reload() })
                }
            }
        }
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
        @can('gudang_delete')
        dtButtons.push(deleteButton)
        @endcan
        $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    })

</script>
@endsection
@endsection