routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::resource('daftar','RegistrationController');
Route::get('daftar-sukses', 'RegistrationController@successReg')->name('daftar-sukses');
Route::post('post-register', 'RegistrationController@store')->name('post-register');
Route::get('kel', 'RegistrationController@getKelurahan')->name('kel');
Route::get('kec', 'RegistrationController@getKecamatan')->name('kec');
Route::get('kab', 'RegistrationController@getKabupaten')->name('kab');
Route::get('verify', 'RegistrationController@verify')->name('daftar.verify');

Route::get('change-passwords', 'ChangePasswordController@index')->name('change-passwords');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password');

Route::get('img/articles/{filename}', 'ImgController@displayArticles')->name('img.articles');
Route::get('img/thumbnail/{filename}', 'ImgController@displayThumbnail')->name('img.thumbnail');
Route::get('img/avatar/{filename}', 'ImgController@displayAvatar')->name('img.avatar');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');
    Route::resource('customer', 'CustomerController');

    Route::resource('item-category', 'ItemCategoryController');
    
    Route::resource('item-unit', 'ItemUnitController');

    Route::resource('item', 'ItemController');
    Route::get('create-packet', 'ItemController@createPacket')->name('create-packet');
    Route::post('post-packet', 'ItemController@postPacket')->name('post-packet');
    Route::get('edit-packet', 'ItemController@editPacket')->name('edit-packet');
    Route::get('show-packet/{id}', 'ItemController@showPacket')->name('show-packet');

    //Transaction
    Route::resource('transaksi', 'TransaksiStokController');
    Route::get('transaksi-in','TransaksiStokController@createIn')->name('transaksi-in');
    Route::get('transaksi-out','TransaksiStokController@createOut')->name('transaksi-out');
    Route::post('transaksi-store-out','TransaksiStokController@storeOut')->name('transaksi-store-out');
    Route::get('report-transaksi', 'TransaksiStokController@reportTransaksi')->name('report-transaksi');
    

    //RO
    Route::resource('ro', 'RequestOrderController');
    Route::get('report-ro', 'RequestOrderController@reportRO')->name('report-ro');
    
    //PO
    Route::resource('po', 'PurchaseOrderController');
    Route::put('update-payment/{id}', 'PurchaseOrderController@updatePayment')->name('update-payment');
    Route::get('report-po', 'PurchaseOrderController@reportPO')->name('report-po');

    //Information
    Route::resource('info', 'InformationController');
    Route::resource('category', 'ArticleCategoryController');

    //getImage
    Route::get('img/ktp/{filename}', 'ImgController@displayKtp')->name('img.ktp');
    Route::get('img/kk/{filename}', 'ImgController@displayKK')->name('img.kk');
    Route::get('img/avatar/{filename}', 'ImgController@displayAvatar')->name('img.avatar');
    Route::get('img/articles/{filename}', 'ImgController@displayArticles')->name('img.articles');
    Route::get('img/thumbnail/{filename}', 'ImgController@displayThumbnail')->name('img.thumbnail');
    
    

    //Master
    Route::resource('gudang', 'GudangController');
    Route::put('rak-update-partial', 'GudangController@updateRakPartials')->name('rak-update-partial');
    Route::put('rak-add-partial', 'GudangController@addRakPartials')->name('rak-add-partial');
    Route::put('rak-del-partial', 'GudangController@delRakPartials')->name('rak-del-partial');
    Route::resource('supplier', 'SupplierController');
    Route::resource('program', 'ProgramController');
    Route::get('report-program', 'ProgramController@reportProgram')->name('report-program');
    Route::resource('wilayah', 'WilayahController');
    Route::resource('provinsi', 'ProvinsiController');
    Route::get('report-member-prov/{id}', 'ProvinsiController@reportMember')->name('report-member-prov');
    Route::resource('kabupaten', 'KabupatenController');
    Route::get('report-member-kab/{id}', 'KabupatenController@reportMember')->name('report-member-kab');
    Route::resource('kecamatan', 'KecamatanController');
    Route::get('report-member-kec/{id}', 'KecamatanController@reportMember')->name('report-member-kec');
    Route::resource('kelurahan', 'KelurahanController');
    Route::get('report-member-kel/{id}', 'KelurahanController@reportMember')->name('report-member-kel');
    Route::resource('master-member', 'MemberController');
    Route::get('report-member', 'MemberController@reportMember')->name('report-member');
    Route::get('member-verified', 'MemberController@indexVerified')->name('member-verified');
    Route::get('edit-verified', 'MemberController@editVerified')->name('edit-verified');
    Route::put('update-verified', 'MemberController@editVerified')->name('update-verified');
    Route::get('edit-korlap/{id}', 'MemberController@editKorlap')->name('edit-korlap');
    Route::put('update-korlap/{id}', 'MemberController@updateKorlap')->name('update-korlap');
    Route::get('member-pending', 'MemberController@indexPending')->name('member-pending');

    //Settings
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');
    Route::get('configuration','ConfigurationController@index')->name('configuration.index');
    Route::get('configuration/create','ConfigurationController@create')->name('configuration.create');
    Route::get('configuration/edit/{id}','ConfigurationController@edit')->name('configuration.edit');
    Route::put('configuration/update/{id}','ConfigurationController@update')->name('configuration.update');
    Route::post('configuration/store','ConfigurationController@store')->name('configuration.store');

    //helper
    Route::get('get-kel', 'HelperController@getKelurahan')->name('get-kel');
    Route::get('get-kec', 'HelperController@getKecamatan')->name('get-kec');
    Route::get('get-kab', 'HelperController@getKabupaten')->name('get-kab');
    Route::get('get-member', 'HelperController@getMember')->name('get-member');
    Route::get('get-rak', 'HelperController@getRak')->name('get-rak');
    
});

resources/views/admin/prov/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.program.title_singular') }}
    </div>

    <div class="card-body">
        <form class="form-material mt-4" action="{{ route("admin.program.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
                <label for="nama">{{ trans('cruds.program.fields.nama') }}*</label>
                <input type="text" id="nama" name="nama" class="form-control" value="{{ old('nama', '') }}">
                @if($errors->has('nama'))
                    <em class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('no_telp') ? 'has-error' : '' }}">
                <label for="no_telp">{{ trans('cruds.program.fields.start') }}*</label>
                <input type="text" onkeypress="return isNumber(event)" id="no_telp" name="no_telp" class="form-control" value="{{ old('no_telp', '') }}">
                @if($errors->has('no_telp'))
                    <em class="invalid-feedback">
                        {{ $errors->first('no_telp') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('no_hp') ? 'has-error' : '' }}">
                <label for="no_hp">{{ trans('cruds.program.fields.end') }}*</label>
                <input type="text" onkeypress="return isNumber(event)" id="no_hp" name="no_hp" class="form-control" value="{{ old('no_hp', '') }}">
                @if($errors->has('no_hp'))
                    <em class="invalid-feedback">
                        {{ $errors->first('no_hp') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('cruds.program.fields.description') }}*</label>
                <input type="text" id="email" name="email" class="form-control" value="{{ old('email', '') }}">
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            
            <div class="form-group {{ $errors->has('ppn') ? 'has-error' : '' }}">
                {{ trans('cruds.program.fields.ppn') }}
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ppn" id="inlineRadio1" value="{{ \App\MstSupplier::YesPpn }}">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ppn" checked id="inlineRadio2" value="{{ \App\MstSupplier::NoPpn }}">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                </div>
                 @if($errors->has('ppn'))
                    <em class="invalid-feedback">
                        {{ $errors->first('ppn') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
                <label for="alamat">{{ trans('cruds.program.fields.alamat') }}*</label>
                <input type="text" id="alamat" name="alamat" class="form-control" value="{{ old('alamat', '') }}">
                @if($errors->has('alamat'))
                    <em class="invalid-feedback">
                        {{ $errors->first('alamat') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">{{ trans('cruds.program.fields.password') }}*</label>
                <input type="password" id="password" name="password" class="form-control" value="{{ old('password', '') }}">
                @if($errors->has('password'))
                    <em class="invalid-feedback">
                        {{ $errors->first('password') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div>
                <button class="btn btn-primary" id="save" type="submit">
                    <span class="spinner-border spin-save spinner-border-sm" role="status" aria-hidden="true"></span>
                    <i class="fa fa-save"></i> {{ trans('global.save') }}
                </button>
                <a href="{{ route('admin.program.index') }}" class="btn btn-default"> 
                    <i class="fa fa-arrow-left"> {{ trans('global.back_to_list') }}</i>
                </a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/prov/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.update') }} {{ trans('cruds.customer.title_singular') }}
    </div>

    <div class="card-body">
        <form class="form-material mt-4" action="{{ route("admin.customer.update",$customer->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
                <label for="nama">{{ trans('cruds.customer.fields.nama') }}*</label>
                <input type="text" id="nama" name="nama" class="form-control" value="{{ old('nama', $customer->nama) }}">
                @if($errors->has('nama'))
                    <em class="invalid-feedback">
                        {{ $errors->first('nama') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('no_telp') ? 'has-error' : '' }}">
                <label for="no_telp">{{ trans('cruds.customer.fields.no_telp') }}*</label>
                <input type="text" onkeypress="return isNumber(event)" id="no_telp" name="no_telp" class="form-control" value="{{ old('no_telp', $customer->no_telp) }}">
                @if($errors->has('no_telp'))
                    <em class="invalid-feedback">
                        {{ $errors->first('no_telp') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('no_hp') ? 'has-error' : '' }}">
                <label for="no_hp">{{ trans('cruds.customer.fields.no_hp') }}*</label>
                <input type="text" onkeypress="return isNumber(event)" id="no_hp" name="no_hp" class="form-control" value="{{ old('no_hp', $customer->no_hp) }}">
                @if($errors->has('no_hp'))
                    <em class="invalid-feedback">
                        {{ $errors->first('no_hp') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('cruds.customer.fields.email') }}*</label>
                <input type="text" id="email" name="email" class="form-control" value="{{ old('email', $customer->email) }}">
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('pic') ? 'has-error' : '' }}">
                <label for="pic">{{ trans('cruds.customer.fields.pic') }}*</label>
                <input type="text" id="pic" name="pic" class="form-control" value="{{ old('pic', $customer->pic) }}">
                @if($errors->has('pic'))
                    <em class="invalid-feedback">
                        {{ $errors->first('pic') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('no_rekening') ? 'has-error' : '' }}">
                <label for="no_rekening">{{ trans('cruds.customer.fields.no_rekening') }}*</label>
                <input type="text" id="no_rekening" name="no_rekening" class="form-control" value="{{ old('no_rekening', $customer->no_rekening) }}">
                @if($errors->has('no_rekening'))
                    <em class="invalid-feedback">
                        {{ $errors->first('no_rekening') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('ppn') ? 'has-error' : '' }}">
                {{ trans('cruds.customer.fields.ppn') }}
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ppn" @if($customer->ppn == \App\MstCustomer::YesPpn) checked @endif id="inlineRadio1" value="{{ \App\MstCustomer::YesPpn }}">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="ppn" @if($customer->ppn == \App\MstCustomer::NoPpn) checked @endif id="inlineRadio2" value="{{ \App\MstCustomer::NoPpn }}">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                </div>
                 @if($errors->has('ppn'))
                    <em class="invalid-feedback">
                        {{ $errors->first('ppn') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
                <label for="alamat">{{ trans('cruds.customer.fields.alamat') }}*</label>
                <input type="text" id="alamat" name="alamat" class="form-control" value="{{ old('alamat', $customer->alamat) }}">
                @if($errors->has('alamat'))
                    <em class="invalid-feedback">
                        {{ $errors->first('alamat') }}
                    </em>
                @endif
                <p class="helper-block">

                </p>
            </div>
            <div>
                <button class="btn btn-primary" id="save" type="submit">
                    <span class="spinner-border spin-save spinner-border-sm" role="status" aria-hidden="true"></span>
                    <i class="fa fa-save"></i> {{ trans('global.update') }}
                </button>
                <a href="{{ route('admin.customer.index') }}" class="btn btn-default"> 
                    <i class="fa fa-arrow-left"> {{ trans('global.back_to_list') }}</i>
                </a>
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/prov/index.blade.php
@extends('layouts.admin')
@section('content')

{{-- @can('customer_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-primary float-right" href="{{ route("admin.provinsi.create") }}">
                <i class="fa fa-plus"></i> {{ trans('global.add') }} {{ trans('cruds.provinsi.title_singular') }}
            </a>
        </div>
    </div>
@endcan --}}
<div class="card">
    <div class="card-header">
        {{ trans('cruds.provinsi.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.provinsi.fields.nama') }}
                        </th>
                        <th>
                            {{ trans('cruds.provinsi.fields.active') }}
                        </th>
                        {{-- <th>
                            &nbsp;
                        </th> --}}
                    </tr>
                </thead>
                <tbody>
                    @foreach($prov as $key => $rows)
                        <tr data-entry-id="{{ $rows->id }}">
                            <td>

                            </td>
                            <td>
                                <a href="{{ route('admin.report-member-prov', $rows->id) }}" target="_blank">
                                    {{ $rows->name ?? '' }}
                                </a>
                            </td>
                            <td>
                                @if($rows->status == 1)
                                    {{ trans('cruds.provinsi.fields.statusactive') }}
                                @elseif($rows->status == 0)
                                    {{ trans('cruds.provinsi.fields.statusinactive') }}
                                @endif
                            </td>
                            {{-- <td>
                                @can('customer_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.provinsi.show', $rows->id) }}">
                                        <i class="fa fa-eye"></i> {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('customer_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.provinsi.edit', $rows->id) }}">
                                        <i class="fa fa-edit"></i> {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('customer_delete')
                                    
                                    <form action="{{ route('admin.provinsi.destroy', $rows->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">
                                            <i class="fa fa-trash"></i> 
                                            {{ trans('global.delete') }}
                                        </button>
                                    </form>
                                @endcan
                            </td> --}}

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
        let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
        let deleteButton = {
            text: deleteButtonTrans,
            url: "{{ route('admin.permissions.massDestroy') }}",
            className: 'btn-danger',
            action: function (e, dt, node, config) {
                var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                    return $(entry).data('entry-id')
                });
                if (ids.length === 0) {
                    alert('{{ trans('global.datatables.zero_selected') }}')
                    return
                }
                if (confirm('{{ trans('global.areYouSure') }}')) {
                    $.ajax({
                    headers: {'x-csrf-token': _token},
                    method: 'POST',
                    url: config.url,
                    data: { ids: ids, _method: 'DELETE' }})
                    .done(function () { location.reload() })
                }
            }
        }
        let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
        @can('gudang_delete')
        dtButtons.push(deleteButton)
        @endcan
        $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    });
</script>
@endsection
@endsection

resources/views/admin/prov/report.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {{ trans('global.report') }} {{ trans('cruds.provinsi.title_singular') }} {{ $title->name }}</title>
    <!-- DataTables -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">
</head>
<body>
    <div class="card">
        <div class="card-header">
        <center> {{ trans('global.report') }} {{ trans('cruds.provinsi.title_singular') }} {{ $title->name }}</center>
        </div>
        <div class="card-body">
            <div class="mb-2">
                <table class="table table-striped" id="table-datatables">
                    {{-- @php
                        echo "<pre>";
                            print_r($report);
                        echo "</pre>";
                    @endphp --}}
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th>
                                {{ trans('cruds.member.fields.no') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.nama') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.nik') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.hp') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.email') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.level_member') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.created_at') }}
                            </th>
                            <th>
                                {{ trans('cruds.member.fields.is_active') }}
                            </th>
                            <th>
                                {{ trans('cruds.provinsi.title_singular') }}
                            </th>
                            {{-- <th>
                                {{ trans('cruds.kabupaten.title_singular') }}
                            </th>
                            <th>
                                {{ trans('cruds.kecamatan.title_singular') }}
                            </th>
                            <th>
                                {{ trans('cruds.kelurahan.title_singular') }}
                            </th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($report as $key => $rows)
                            <tr>
                                <td>
                                    {{ $key+1 }}
                                </td>
                                <td>
                                    @php
                                        $kec = str_pad($rows->kecid,4,"0",STR_PAD_LEFT);   
                                    @endphp
                                    <a href="{{ route('admin.master-member.show', $rows->userid) }}" target="_blank">
                                        {{ $rows->provid ?? '-' }}.{{ $kec ?? '-' }}.{{ $rows->no_member ?? '-' }}
                                    </a>
                                </td>
                                <td>
                                    {{ $rows->name ?? '-' }}
                                </td>
                                <td>
                                    {{ $rows->nik ?? '-' }}
                                </td>
                                <td>
                                    {{ $rows->no_hp ?? '-' }}
                                </td>
                                <td>
                                    {{ $rows->email ?? '-' }}
                                </td>
                                <td>
                                    @if ($rows->status_korlap == 0)
                                        Anggota
                                    @elseif ($rows->status_korlap == 1)
                                        Korlap
                                    @endif
                                </td>
                                <td>
                                    {{ $rows->created_at ?? '-' }}
                                </td>
                                <td>
                                    @if($rows->is_active == 1)
                                        {{ trans('cruds.member.fields.active') }}
                                    @elseif($rows->is_active == 0)
                                        {{ trans('cruds.member.fields.inactive') }}
                                    @endif
                                </td>
                                <td>
                                    {{ $rows->provname ?? '' }}
                                </td>
                                {{-- <td>
                                    {{ $rows->kabname ?? '' }}
                                </td>
                                <td>
                                    {{ $rows->kecname ?? '' }}
                                </td>
                                <td>
                                    {{ $rows->kelname ?? '' }}
                                </td> --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script type="text/javascript"> 
        $(document).ready(function () {
            $('#table-datatables').DataTable({
                dom: 'Bfrtip',
                searching: false,
                paging: false,
                buttons: ['csv', 'excel']
            });
        });
    </script>
</body>
</html>